In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([[1,2],[2,3]],dtype=complex)

array([[1.+0.j, 2.+0.j],
       [2.+0.j, 3.+0.j]])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [7]:
np.ones((2,3,4),dtype=complex)

array([[[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]],

       [[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]]])

In [8]:
np.arange(5)


array([0, 1, 2, 3, 4])

In [9]:
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

In [10]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [11]:
np.linspace(0,2,9,endpoint=False)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778])

In [12]:
np.sin(np.pi/4)

0.7071067811865475

In [13]:
A = np.array([[3,4],[2,4]])
B = np.array([[3],[2]])

In [14]:
A.dot(B)

array([[17],
       [14]])

In [15]:
A @ B 

array([[17],
       [14]])

In [18]:
np.random.random((2,3))

array([[0.06347437, 0.71357446, 0.79173685],
       [0.57721965, 0.79701328, 0.11768288]])

In [28]:
np.random.random((2,3)).ravel().reshape(3,2)

array([[0.9619946 , 0.17973846],
       [0.97663938, 0.22360793],
       [0.98976788, 0.15044948]])

In [34]:
C = np.array([[2,4],[9,-2]])
np.sqrt(C)

<ipython-input-34-fc03d91312f8>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(C)


array([[1.41421356, 2.        ],
       [3.        ,        nan]])

In [33]:
C = np.array([[2,4],[9,-2]],dtype=complex)
np.sqrt(C)

array([[1.41421356+0.j        , 2.        +0.j        ],
       [3.        +0.j        , 0.        +1.41421356j]])

In [37]:
C.T

array([[ 2,  9],
       [ 4, -2]])

In [38]:
np.arange(10)**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [41]:
np.arange(10)[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
def f(x,y):
    return (x+1) ** (y+1)

D = np.fromfunction(f,(3,4))
print(D)

[[ 1.  1.  1.  1.]
 [ 2.  4.  8. 16.]
 [ 3.  9. 27. 81.]]


In [53]:
D[0:2,1]

array([1., 4.])

In [54]:
print(D)

[[ 1.  1.  1.  1.]
 [ 2.  4.  8. 16.]
 [ 3.  9. 27. 81.]]


In [56]:
for i in D:
    print(i)

[1. 1. 1. 1.]
[ 2.  4.  8. 16.]
[ 3.  9. 27. 81.]


In [58]:
for i in D.flat:
    print(i)

1.0
1.0
1.0
1.0
2.0
4.0
8.0
16.0
3.0
9.0
27.0
81.0


In [59]:
for i in D.ravel():
    print(i)

1.0
1.0
1.0
1.0
2.0
4.0
8.0
16.0
3.0
9.0
27.0
81.0


In [61]:
print(D.shape)

(3, 4)


In [87]:
a = np.random.random((2,3))
b = np.random.random((4,3))
print(a)
print(b)
c = np.vstack((a,b))
print(c)

[[0.07975858 0.95092638 0.71298293]
 [0.77125933 0.72938594 0.45624456]]
[[0.04497535 0.61051439 0.41443963]
 [0.29644677 0.44474903 0.53890376]
 [0.5390718  0.03076058 0.16181721]
 [0.62214635 0.30064133 0.71688255]]
[[0.07975858 0.95092638 0.71298293]
 [0.77125933 0.72938594 0.45624456]
 [0.04497535 0.61051439 0.41443963]
 [0.29644677 0.44474903 0.53890376]
 [0.5390718  0.03076058 0.16181721]
 [0.62214635 0.30064133 0.71688255]]


In [90]:
print(np.hsplit(c,3)[1])

[[0.95092638]
 [0.72938594]
 [0.61051439]
 [0.44474903]
 [0.03076058]
 [0.30064133]]


In [93]:
d = c.copy()
e = c.view()
c[2,1]=np.nan
print(c)
print(d)
print(e)

[[0.07975858 0.95092638 0.71298293]
 [0.77125933 0.72938594 0.45624456]
 [0.04497535        nan 0.41443963]
 [0.29644677 0.44474903 0.53890376]
 [0.5390718  0.03076058 0.16181721]
 [0.62214635 0.30064133 0.71688255]]
[[0.07975858 0.95092638 0.71298293]
 [0.77125933 0.72938594 0.45624456]
 [0.04497535 0.61051439 0.41443963]
 [0.29644677 0.44474903 0.53890376]
 [0.5390718  0.03076058 0.16181721]
 [0.62214635 0.30064133 0.71688255]]
[[0.07975858 0.95092638 0.71298293]
 [0.77125933 0.72938594 0.45624456]
 [0.04497535        nan 0.41443963]
 [0.29644677 0.44474903 0.53890376]
 [0.5390718  0.03076058 0.16181721]
 [0.62214635 0.30064133 0.71688255]]


In [104]:
E = np.array([[4,6,8],[4,8,3],[4,5,4]])
E.shape

(3, 3)

In [106]:
print(np.linalg.eig(E))

(array([15.18155915, -1.48621343,  2.30465428]), array([[-0.65775213, -0.87479192,  0.6705039 ],
       [-0.57138155,  0.234851  , -0.65472083],
       [-0.49080063,  0.42377364,  0.34894864]]))


In [107]:
print(np.linalg.det(E))

-51.999999999999986


In [108]:
print(np.linalg.inv(E))

[[-0.32692308 -0.30769231  0.88461538]
 [ 0.07692308  0.30769231 -0.38461538]
 [ 0.23076923 -0.07692308 -0.15384615]]
